openapi: "3.0.0"
info:
  title: "T-shirt store API"
  description: "project on create api for ecom store"
  version: 1.1.0
  contact:
    email: "pranay@gmail.com"
    url: "https://pra.dev"

#servers:
#  - url: "https://localhost:4000/api/v1"
#    description: for local host -secure
#  - url: "http://localhost:4000/api/v1"
#    description: for local host -regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host -secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
  - url: "http://localhost:4000/api/v1"
    description: for local host -regular

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer